config/routes.rb
Rails.application.routes.draw do

  root 'books#index'
  resources :books do
    resources :chapters
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :path
  has_many :chapters, dependent: :destroy

end

app/models/chapter.rb
class Chapter
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :number, type: Integer
  field :content
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update]

  def index
    @books = Book.all
  end

  def edit
  end

  def update
    if @book.update book_params
      flash[:success] = 'Cập nhật thành công'
      redirect_to edit_book_path(@book)
    else
      render :edit, errors: @chapter.errors
    end
  end

  def new
    @book = Book.new
  end

  private
  def book_params
    params.require(:book).permit(:name)
  end

  def set_book
    @book = Book.or({id: params[:id]}, {path: params[:id]}).first
    raise ActionController::RoutingError.new "Not Found." unless @book
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_book
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  def index
    @page = params["page"] || 1
    @chapters = @book.chapters.page(@page).per(10)
  end

  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new chapter_params
    @chapter.book = @book
    if @chapter.save
      flash[:success] = 'Đã thêm chương mới'
      redirect_to book_chapters_path(@book)
    else
      render :new, errors: @chapter.errors
    end
  end

  def show
    unless @chapter.present?
      chapter_number = params[:id].to_i
      if params[:next].present?
        @chapter = @book.chapters.where(:number.gt => chapter_number).order_by({"number": "asc"}).first
        @chapter = @book.chapters.where(number: chapter_number - 1).first unless @chapter.present?
      end
      if params[:prev].present?
        @chapter = @book.chapters.where(:number.lte => chapter_number).order_by({"number": "desc"}).first
        @chapter = @book.chapters.where(number: chapter_number + 1).first unless @chapter.present?
      end
    end
  end

  def edit
  end

  def update
    if @chapter.update chapter_params
      flash[:success] = 'Cập nhật thành công'
      redirect_to edit_book_chapter_path(@book, @chapter)
    else
      render :edit, errors: @chapter.errors
    end
  end

  def destroy
    if @chapter.destroy
      flash[:danger] = 'Đã xoá chương'
      redirect_to book_chapters_path(@book)
    else
      render :new, errors: @chapter.errors
    end
  end

  private
  def chapter_params
    params.require(:chapter).permit(:name, :number, :content)
  end

  def set_book
    @book = Book.or({id: params[:book_id]}, {path: params[:book_id]}).first
    raise ActionController::RoutingError.new "Not Found." unless @book
  end

  def set_chapter
    @chapter = Chapter.or({id: params[:id]}, {number: params[:id]}).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/books/edit.html.slim
javascript:
  console.log("aaa")
.chapter-edit
  - flash.each do |key, value|
    div*{class: "alert alert-#{key} fade in alert-dismissible"}
      a.close data-dismiss="alert" aria-label="close" &times;
      = value
  = form_for @book, url: book_path do |f|
    label for="name" Tên Sách
    = f.text_field :name, class: "form-control"
    = f.submit "Cập nhật", class: "btn btn-primary btn-default"

app/views/books/index.html.slim
.chapter-index
  button.btn.btn-primary = link_to "new", new_book_path
  - flash.each do |key, value|
    div*{class: "alert alert-#{key} fade in alert-dismissible"}
      a.close data-dismiss="alert" aria-label="close" &times;
      = value
  table
    tbody
      - @books.each do |book|
        tr
          td = link_to book.name, book_chapters_path(book.path)
          td
            button.btn.btn-secondary = link_to "Sửa", edit_book_path(book.path)
          td
            button.btn.btn-danger = link_to book_path(book), data: {no_turbolink: true}, class: "red", method: :delete,
          data: { confirm: "Chắc chắn xoá không?" }
            | Xoá

app/views/books/new.html.slim
aaa

app/views/chapters/edit.html.slim
.chapter-edit
  - flash.each do |key, value|
    div*{class: "alert alert-#{key} fade in alert-dismissible"}
      a.close data-dismiss="alert" aria-label="close" &times;
      = value
  = form_for @chapter, url: book_chapter_path do |f|
    label for="chapter_name" Tên Chương
    = f.text_field :name, class: "form-control"
    label for="chapter_number" Số
    = f.text_field :number, class: "form-control"
    label for="chapter_content" Nội dung
    = f.text_area :content, class: "form-control", rows: "30"
    = f.submit "Cập nhật", class: "btn btn-primary btn-default"

app/views/chapters/index.html.slim
.chapter-index
  h1 = @book.name
  = link_to "Mới", new_book_chapter_path(@book), class: "btn btn-primary"
  - flash.each do |key, value|
    div*{class: "alert alert-#{key} fade in alert-dismissible"}
      a.close data-dismiss="alert" aria-label="close" &times;
      = value
  .newest
    h3 CHƯƠNG MỚI
    table
      tbody
        - @book.chapters.order_by({"number": "desc"}).limit(5).each do |chapter|
          tr
            td
              a href="#{book_chapter_path(@book.path, chapter.number)}"
                = "Chương #{chapter.number}: #{chapter.name}"
  .chapters
    h3 DANH SÁCH CHƯƠNG
    table
      tbody
        - @chapters.order_by({"number": "asc"}).each do |chapter|
          tr
            td
              a href="#{book_chapter_path(@book.path, chapter.number)}"
                = "Chương #{chapter.number}: #{chapter.name}"
            td = link_to "edit", edit_book_chapter_path(@book.path, chapter.number), class: "btn btn-info"
            td = link_to book_chapter_path(@book, chapter), data: {no_turbolink: true}, class: "btn btn-danger", method: :delete,
            data: { confirm: "Chắc chắn xoá không?" }
              | Xoá

    = paginate @chapters

app/views/chapters/new.html.slim
.chapter-edit
  - flash.each do |key, value|
    div*{class: "alert alert-#{key} fade in alert-dismissible"}
      a.close data-dismiss="alert" aria-label="close" &times;
      = value
  = form_for @chapter, url: book_chapters_path do |f|
    label for="chapter_name" Tên Chương
    = f.text_field :name, class: "form-control"
    label for="chapter_number" Số
    = f.text_field :number, class: "form-control"
    label for="chapter_content" Nội dung
    = f.text_area :content, class: "form-control", rows: "30"
    = f.submit "Tạo", class: "btn btn-primary btn-default"

app/views/chapters/show.html.slim
.chapter-view

  .title
    p.book-name = @book.name
    p.chapter-name = "Chương #{@chapter.number}: #{@chapter.name}"
    = select_tag "chapter_select",
      options_for_select(@book.chapters.order_by({"number": "asc"}).map {|c| ["Chương: #{c.number}: #{c.name}", book_chapter_path(@book.path, c.number)]}, book_chapter_path(@book.path, @chapter.number)),
      :onchange => "document.location.href=this.value",
      :class => "form-control"
    p.break &#42;&#42;&#42;&#42;&#42;&#42;&#42;&#42;&#42;
  .content
    = @chapter.content
  .control-button
    = link_to "▲", book_chapter_path(@book.path, @chapter.number.to_i - 1, prev: true), class: "btn btn-outline-primary scroll-btn top"
    = link_to "▼", book_chapter_path(@book.path, @chapter.number.to_i + 1, next: true), class: "btn btn-outline-primary scroll-btn bottom"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doctruyen</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>